---
title: "Titel anpassen"
subtitle: "Untertitel hinzufügen"
author: 
  - name: "Vorname Nachname"
    email: "vorname.nachname@bi.zh.ch"
    affiliation: "Organisationsname"
date: last-modified
date-format: "DD.MM.YYYY"
lang: de
# Klassifikation in Präambel definieren

format:
    pdf:
        include-in-header:
        - _extensions/biplaR-pdf/preamble.tex
        template: _extensions/biplaR-pdf/tmplt.tex
        documentclass: biplaRartcl
        fig-pos: "H"
        # fig-align: "left"
        # fig-height: 3
        latex-input-paths:
            - _extensions/biplaR-pdf/tex/xelatex/biplaRartcl
            - _extensions/biplaR-pdf/tex/xelatex/biplaRartcl/assets
            - _extensions/biplaR-pdf/tex/xelatex/biplaRartcl/img

cap-location: top

execute:
    warning: false
    echo: false

---

```{r setup, include=FALSE}
if (knitr::is_latex_output()) {
  knitr::opts_chunk$set(dev = "cairo_pdf")
}

# grab your data

source <- "Bildungsplanung Kanton Zürich 2025"
```


# Ausgangslage

```{r}
# transform, analyse and present your data
```

# Fazit

# Anhang
